version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: "increase"
    groups:
      gems:
        patterns:
          - "*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
